# Generated by Django 5.2 on 2025-05-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_diet_goals_target_diet_restrictions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='diet_goals',
            new_name='preferred_diet',
        ),
    ]
