# Generated by Django 5.2 on 2025-05-14 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_rename_diet_goals_target_preferred_diet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='preferred_focus',
            new_name='fitness_focus',
        ),
    ]
