# Generated by Django 5.2 on 2025-04-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gif_url', models.URLField()),
                ('target_muscles', models.JSONField()),
                ('body_parts', models.JSONField()),
                ('equipments', models.JSONField()),
            ],
        ),
    ]
